-- AlterTable
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "liveUrl" TEXT;

-- AlterTable
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "backcomType" TEXT;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "backcomValue" TEXT;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "rebateType" TEXT;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "bonusType" TEXT;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "highlightOffer" TEXT;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "offerConditions" TEXT;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "payoutCycle" TEXT;
