/** Crypto heatmap category labels for treemap grouping. */

const CRYPTO_CATEGORY: Record<string, string> = {
  BTC: "Layer 1",
  ETH: "Layer 1",
  SOL: "Layer 1",
  BNB: "Exchange",
  XRP: "Payments",
  ADA: "Layer 1",
  DOGE: "Meme",
  AVAX: "Layer 1",
  DOT: "Layer 1",
  LINK: "DeFi",
  USDT: "Stablecoin",
  USDC: "Stablecoin",
  TRX: "Layer 1",
  SHIB: "Meme",
  BCH: "Layer 1",
  NEAR: "Layer 1",
  LTC: "Payments",
  UNI: "DeFi",
  ICP: "Layer 1",
  ETC: "Layer 1",
  RNDR: "AI",
  HBAR: "Layer 1",
  ATOM: "Layer 1",
  FIL: "Storage",
  XLM: "Payments",
  XMR: "Privacy",
  ARB: "Layer 2",
  MKR: "DeFi",
  VET: "Enterprise",
  OP: "Layer 2",
  INJ: "DeFi",
  GRT: "Infrastructure",
  IMX: "Gaming",
  AAVE: "DeFi",
  ALGO: "Layer 1",
  FTM: "Layer 1",
  THETA: "Media",
  FLOW: "Gaming",
  QNT: "Enterprise",
  SAND: "Gaming",
  MANA: "Gaming",
  AXS: "Gaming",
  EOS: "Layer 1",
  XTZ: "Layer 1",
  NEO: "Layer 1",
  KCS: "Exchange",
  IOTA: "IoT",
  ZEC: "Privacy",
  DASH: "Payments",
}

export function cryptoCategory(symbol: string): string {
  const key = symbol.replace(/\/USD$/i, "").toUpperCase()
  return CRYPTO_CATEGORY[key] ?? "Altcoins"
}
