export const SITE_NAME = "BTrading Market Insights"
export const SITE_NAME_SHORT = "BTrading"
export const SITE_DOMAIN = "https://btrading.org"
export const SITE_HOST = "btrading.org"
export const SITE_LOGO = "/brand/logo.png"
export { SITE_EMAIL } from "./contact"
export const SITE_PRIVACY_EMAIL = "privacy@btrading.com"
